### ISSUE TITLE
Migrate to Go Modules

### ISSUE THREAD

**Issue by AbhayAysola** [twystd/tweetnacl-golang#1]
https://blog.golang.org/migrating-to-go-modules

**Comment by twystd** [comment]
Hi,

Have restructured the project to support modules and added `go.mod`. The changes have been committed to the `master` branch but not yet released - please include the project using:
```
go get -u github.com/twystd/tweetnacl-go@593e4d1abe85e81a332745dece57924d3d440412
```

I'll do a release once you've confirmed it works as expected.

**Comment by AbhayAysola** [comment]
> Hi,
> 
> Have restructured the project to support modules and added `go.mod`. The changes have been committed to the `master` branch but not yet released - please include the project using:
> 
> ```
> go get -u github.com/twystd/tweetnacl-go@593e4d1abe85e81a332745dece57924d3d440412
> ```
> 
> I'll do a release once you've confirmed it works as expected.

Cool, it works as expected 👍🏼 
I have another problem though,
```
package main

import (
	"fmt"	
	"github.com/twystd/tweetnacl-go/tweetnacl"
)

func main() {
	fmt.Print(tweetnacl.CryptoSignKeyPair())
}
```
This code doesn't exit, it justs runs forever with no output. The other methods work fine though.

**Comment by twystd** [comment]
Hmm, it seems to work ok for me:
```
&{[220 205 30 174 86 23 3 219 162 197 29 46 117 120 119 47 120 134 70 201 164 83 156 216 166 201 200 52 222 171 18 106] [209 174 195 32 19 97 174 163 178 110 195 45 0 255 114 33 47 89 137 171 58 170 19 137 157 173 182 249 148 56 49 222 220 205 30 174 86 23 3 219 162 197 29 46 117 120 119 47 120 134 70 201 164 83 156 216 166 201 200 52 222 171 18 106]} <nil>
```

Can you give me some details of the system/operating system you're using? 

And can you try printing a newline at the end of your output (possibly your OS/terminal requires a newline to display anything) ?

**Comment by AbhayAysola** [comment]
I tried doing this 
```
package main

import (
	"fmt"	
	"github.com/twystd/tweetnacl-go/tweetnacl"
)

func main() {
	pair, _ := tweetnacl.CryptoSignKeyPair()
	fmt.Print(pair, '\n')
}
```
I get the same issue.
I'm using Windows 10

**Comment by twystd** [comment]
Isolated the problem to the `/dev/urandom` the entropy source not being supported directly on _Windows_. I've pushed a provisional fix to the `master` branch which you can pull using:
```
go get -u github.com/twystd/tweetnacl-go@master
```

The patch seems to work on _Windows Server 2016_ - can you please try it out and let me know whether it also fixes the issue on _Windows 10_?

**Comment by AbhayAysola** [comment]
Yep it works now, thanks for all the help :)
